SP_CHARS = [
    "char_513_apionr",  # 郁金香
    "char_608_acpion",  # 郁金香
    "char_508_aguard",  # Sharp
    "char_609_acguad",  # Sharp
    "char_610_acfend",  # Mechanist
    "char_511_asnipe",  # Stormeye
    "char_611_acnipe",  # Stormeye
    "char_612_accast",  # Pith
    "char_509_acast",  # Pith
    "char_613_acmedc",  # Touch
    "char_510_amedic",  # Touch
    "char_614_acsupo",  # Raidian
    "char_615_acspec",  # Misery
    "char_504_rguard",  # 预备干员-近战
    "char_505_rcast",  # 预备干员-术师
    "char_506_rmedic",  # 预备干员-后勤
    "char_507_rsnipe",  # 预备干员-狙击
    "char_514_rdfend",  # 预备干员-重装
    "char_600_cpione",  # 预备干员-先锋
    "char_601_cguard",  # 预备干员-近卫
    "char_602_cdfend",  # 预备干员-重装
    "char_603_csnipe",  # 预备干员-狙击
    "char_604_ccast",  # 预备干员-术师
    "char_605_cmedic",  # 预备干员-医疗
    "char_606_csuppo",  # 预备干员-辅助
    "char_607_cspec",  # 预备干员-特种
]
