name: Build

on:
    push:
      branches:
      - "**"

      paths:
        - ".github/workflows/**"
        - "src/**"
        - "version/**"
        - "**.py"

    schedule:
      - cron: '0 16 * * *' # UTC+8 00:00 [zh_CN]
      - cron: '0 15 * * *'  # UTC+9 00:00 [ja_JP , ko_KR]
      - cron: '0 7 * * *'  # UTC-7 00:00 [en_US]

jobs:
    Build:
      runs-on: macos-latest
      steps:
        - name: Checkout Code
          uses: actions/checkout@v4

        - name: Checkout yuanyan3060/ArknightsGameResource
          uses: actions/checkout@v4
          with:
            repository: yuanyan3060/ArknightsGameResource
            path: avatar
            sparse-checkout-cone-mode: false
            sparse-checkout: |
              avatar

        - name: Checkout MaaAssistantArknights/MaaAssistantArknights
          uses: actions/checkout@v4
          with:
            repository: MaaAssistantArknights/MaaAssistantArknights
            path: cache
            sparse-checkout-cone-mode: false
            sparse-checkout: |
              resource/version.json
              resource/battle_data.json

        - name: Download Latest Release
          uses: robinraju/release-downloader@v1
          with:
            latest: true
            fileName: "version.json"
            token: ${{ secrets.GITHUB_TOKEN }}

        - name: Setup Python
          uses: actions/setup-python@v5
          with:
            python-version: "3.12"

        - name: Run build.py
          run: |
            pip install -r requirements.txt
            python build.py ${{ secrets.GITHUB_TOKEN }}

        - name: Upload GameData Artifact
          if: env.release == 'true'
          uses: actions/upload-artifact@v4
          with:
            name: GameData
            path: |
              build/*

        - name: Upload GameData Artifact(Noavatar)
          if: env.release == 'true'
          uses: actions/upload-artifact@v4
          with:
            name: GameData(NoAvatar)
            path: |
              build/*
              !build/avatar

        - name: Release Preparation
          if: env.release == 'true'
          run: |
            cd build
            zip -r -q GameData.zip .
            cd ..
            python checksums.py

        - name: Create Release
          if: env.release == 'true'
          uses: softprops/action-gh-release@v2
          with:
            tag_name: ${{ env.update_time }}
            make_latest: true
            files: |
              build/GameData.zip
              build/charater.json
              build/version.json
            body: |
              Sha256
              ${{ env.Sha }}