name: Auto Build

on:
    push:
      branches:
      - "**"

      paths:
        - ".github/workflows/**"
        - "src/**"
        - "version/**"
        - "**.py"

    schedule:
      - cron: '30 3 * * *'
      - cron: '30 9 * * *'
      - cron: '30 2 * * *'
      - cron: '30 8 * * *'
      - cron: '30 18 * * *'
      - cron: '30 0 * * *'

jobs:
    meta:
      runs-on: macos-latest
      steps:
        - name: Checkout Code
          uses: actions/checkout@v4.2.1

        - name: Setup Python
          uses: actions/setup-python@v5.2.0
          with:
            python-version: "3.12"
        - name: Run meta.py
          run: |
            python meta.py

      outputs:
        timestamp: ${{ env.timestamp }}
        enable_workflow: ${{ env.enable_workflow }}
        create_release: ${{ env.create_release }}

    zh_CN:
        needs: meta
        if: ${{ needs.meta.outputs.enable_workflow }}
        uses: ./.github/workflows/data.yml
        with:
          checkout_repo: yuanyan3060/ArknightsGameResource
          checkout_path: cache/zh_CN/
          checkout_files: |
            avatar
            version
            gamedata/excel/character_table.json
          lang: zh_CN
          timezone: Asia/Shanghai
          timestamp: ${{ needs.meta.outputs.timestamp }}

    en_US:
        needs: [meta,zh_CN]
        uses: ./.github/workflows/data.yml
        with:
          checkout_files: en_US/gamedata/excel/character_table.json
          lang: en_US
          timezone: America/Dawson
          timestamp: ${{ needs.meta.outputs.timestamp }}

    ja_JP:
        needs: [meta,zh_CN]
        uses: ./.github/workflows/data.yml
        with:
          checkout_files: ja_JP/gamedata/excel/character_table.json
          lang: ja_JP
          timezone: Asia/Tokyo
          timestamp: ${{ needs.meta.outputs.timestamp }}

    ko_KR:
        needs: [meta,zh_CN]
        uses: ./.github/workflows/data.yml
        with:
          checkout_files: ko_KR/gamedata/excel/character_table.json
          lang: ko_KR
          timezone: Asia/Seoul
          timestamp: ${{ needs.meta.outputs.timestamp }}

    Release:
        needs: [meta,zh_CN,en_US,ja_JP,ko_KR]
        runs-on: macos-latest
        if: (needs.meta.outputs.create_release == 'true') && (needs.zh_CN.outputs.release == 'true' || needs.en_US.outputs.release == 'true' || needs.ja_JP.outputs.release == 'true' || needs.ko_KR.outputs.release == 'true')
        env:
          timestamp: ${{ needs.meta.outputs.timestamp }}
        steps:
        - name: Checkout Code
          uses: actions/checkout@v4.2.1

        - name: Download Artifacts
          uses: actions/download-artifact@v4.1.8
          with:
            path: assets

        - name: Create Zip and Move Files
          run: |
            echo "::notice:: zh_CN: ${{ needs.zh_CN.outputs.release }}"
            echo "::notice:: en_US: ${{ needs.en_US.outputs.release }}"
            echo "::notice:: ja_JP: ${{ needs.ja_JP.outputs.release }}"
            echo "::notice:: ko_KR: ${{ needs.ko_KR.outputs.release }}"

            mkdir -p version && cd version
            mkdir -p zh_CN && mkdir -p en_US && mkdir -p ja_JP && mkdir -p ko_KR && cd ..

            cd assets
            cd avatar-zh_CN-${{ env.timestamp }}
            zip -r -q avatar-zh_CN.zip .
            mv avatar-zh_CN.zip ..

            cd ../zh_CN-${{ env.timestamp }} && mv zh_CN-version ..
            zip -r -q zh_CN.zip .
            mv zh_CN.zip ..
            mv -f version ../../version/zh_CN/

            cd ../en_US-${{ env.timestamp }} && mv en_US-version ..
            zip -r -q en_US.zip .
            mv en_US.zip ..
            mv -f version ../../version/en_US/

            cd ../ja_JP-${{ env.timestamp }} && mv ja_JP-version ..
            zip -r -q ja_JP.zip .
            mv ja_JP.zip ..
            mv -f version ../../version/ja_JP/

            cd ../ko_KR-${{ env.timestamp }} && mv ko_KR-version ..
            zip -r -q ko_KR.zip .
            mv ko_KR.zip ..
            mv -f version ../../version/ko_KR/

        - name: Commit zh_CN Version
          if: ${{ needs.zh_CN.outputs.release == 'true' }}
          uses: EndBug/add-and-commit@v9.1.4
          with:
            author_name: github-actions
            author_email: github-actions[bot]@users.noreply.github.com
            message: '[zh_CN] ${{ needs.zh_CN.outputs.ver }}'
            add: 'version/zh_CN/version'

        - name: Commit en_US Version
          if: ${{ needs.en_US.outputs.release == 'true' }}
          uses: EndBug/add-and-commit@v9.1.4
          with:
            author_name: github-actions
            author_email: github-actions[bot]@users.noreply.github.com
            message: '[en_US] ${{ needs.en_US.outputs.ver }}'
            add: 'version/en_US/version'

        - name: Commit ja_JP Version
          if: ${{ needs.ja_JP.outputs.release == 'true' }}
          uses: EndBug/add-and-commit@v9.1.4
          with:
            author_name: github-actions
            author_email: github-actions[bot]@users.noreply.github.com
            message: '[ja_JP] ${{ needs.ja_JP.outputs.ver }}'
            add: 'version/ja_JP/version'

        - name: Commit ko_KR Version
          if: ${{ needs.ko_KR.outputs.release == 'true' }}
          uses: EndBug/add-and-commit@v9.1.4
          with:
            author_name: github-actions
            author_email: github-actions[bot]@users.noreply.github.com
            message: '[ko_KR] ${{ needs.ko_KR.outputs.ver }}'
            add: 'version/ko_KR/version'

        - name: Create Release
          uses: softprops/action-gh-release@v2.1.0
          with:
            tag_name: ${{ env.timestamp }}
            make_latest: true
            files: |
              assets/avatar-zh_CN.zip
              assets/zh_CN.zip
              assets/en_US.zip
              assets/ja_JP.zip
              assets/ko_KR.zip
              assets/zh_CN-version
              assets/en_US-version
              assets/ja_JP-version
              assets/ko_KR-version
            body: |
             - zh_CN: ${{ needs.zh_CN.outputs.ver }}
             - en_US: ${{ needs.en_US.outputs.ver }}
             - ja_JP: ${{ needs.ja_JP.outputs.ver }}
             - ko_KR: ${{ needs.ko_KR.outputs.ver }}