name: Checksums

on:
  workflow_call

jobs:
    Run:
        runs-on: macos-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Download Release
              uses: robinraju/release-downloader@v1
              with:
                latest: true
                fileName: "*.zip"
                token: ${{ secrets.GITHUB_TOKEN }}

            - name: Setup Python
              uses: actions/setup-python@v5
              with:
                python-version: "3.12"

            - name: Update Checksums
              run: |
                pip install -r requirements.txt
                python checksums.py ${{ secrets.GITHUB_TOKEN }}
